"""Offline accent-cache contracts for the VoiceProbe v3 audio boundary.

This module deliberately has no MeloTTS import.  Live processes only validate
metadata and read production-format PCM that was generated by the repo tool.
"""

from __future__ import annotations

import hashlib
import atexit
import json
import os
import select
import subprocess
import struct
import tempfile
import time
import wave
import threading
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

from .medication_refill import CORRECTION_DOSE, MEDICATION, PHARMACY_PREFERENCE, SCENARIO_ID as MEDICATION_SCENARIO_ID
from .self_pay_location import SCENARIO_ID as OFFICE_SCENARIO_ID
from .doctor_specialist import SCENARIO_ID as DOCTOR_SCENARIO_ID, FIRST_NAME as DOCTOR_FIRST_NAME, LAST_NAME as DOCTOR_LAST_NAME, FULL_NAME as DOCTOR_FULL_NAME
from .farthest_date import SCENARIO_ID as FARTHEST_DATE_SCENARIO_ID, farthest_date_phrase_inventory
from .models import PatientFacts
from .prerequisite import _join_response_parts


ACCENT_ENV = "VOICEPROBE_ACCENT_MODE"
ACCENT_NONE = "none"
ACCENT_MELO_INDIA = "melo_india"
ACCENT_CHATTERBOX_KOREAN_HEAVY = "chatterbox_korean_heavy"
MELO_SPEAKER = "EN_INDIA"
KOREAN_REFERENCE = "synthetic_local_korean_reference_v1"
CACHE_FORMAT_VERSION = "pcm_s16le_8000_mono_v1"
SAMPLE_RATE = 8_000
CHANNELS = 1
SAMPLE_WIDTH = 2
ENCODING = "signed-linear-pcm16-little-endian"
DEFAULT_CACHE_ROOT = Path(__file__).resolve().parents[3] / "artifacts/accent-cache"
DEFAULT_MELO_PYTHON = Path.home() / ".venvs/voiceprobe-accent/bin/python"
MELO_CACHE_BUILDER = Path(__file__).resolve().parents[3] / "tools/voiceprobe_build_accent_cache.py"
# A genuinely cold standalone worker measured 19.99s to publish its flushed
# ready message on this host.  Give the single background worker three cold
# starts' worth of headroom for load variance; this bound is used only when an
# unexpected cache miss actually needs the worker.
MELO_MEASURED_COLD_START_SECONDS = 20.0
MELO_STARTUP_TIMEOUT_SECONDS = MELO_MEASURED_COLD_START_SECONDS * 3
MELO_RENDER_TIMEOUT_SECONDS = 15.0


def accent_mode_from_environment() -> str:
    value = os.environ.get(ACCENT_ENV, ACCENT_NONE).strip().casefold() or ACCENT_NONE
    if value not in {ACCENT_NONE, ACCENT_MELO_INDIA, ACCENT_CHATTERBOX_KOREAN_HEAVY}:
        raise ValueError(f"{ACCENT_ENV} must be one of: none, melo_india, chatterbox_korean_heavy")
    return value


def accent_cache_key(text: str, *, accent_mode: str = ACCENT_MELO_INDIA) -> str:
    if not isinstance(text, str) or not text:
        raise ValueError("Accent cache identity requires non-empty exact text")
    identity = {
        "accent_mode": accent_mode,
        "format_version": CACHE_FORMAT_VERSION,
        "speaker": MELO_SPEAKER if accent_mode == ACCENT_MELO_INDIA else KOREAN_REFERENCE,
        "text": text,
    }
    wire = json.dumps(identity, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(wire.encode("utf-8")).hexdigest()


class PersistentMeloIndiaRenderer:
    """Serialized client for one asynchronously warmed Melo/EN_INDIA worker."""

    def __init__(self, *, startup_timeout: float = MELO_STARTUP_TIMEOUT_SECONDS,
                 render_timeout: float = MELO_RENDER_TIMEOUT_SECONDS) -> None:
        self._startup_timeout = startup_timeout
        self._render_timeout = render_timeout
        self._lock = threading.Lock()
        self._ready = threading.Event()
        self._startup_failure: BaseException | None = None
        self._temporary = tempfile.TemporaryDirectory(prefix="voiceprobe-melo-worker-")
        self._process: subprocess.Popen[str] | None = None
        self._start()

    def _start(self) -> None:
        python = Path(os.environ.get("VOICEPROBE_ACCENT_PYTHON", str(DEFAULT_MELO_PYTHON)))
        if not python.is_file():
            raise RuntimeError(f"Melo environment is missing: {python}")
        environment = os.environ.copy()
        environment.update({"NUMBA_CACHE_DIR": str(Path(self._temporary.name) / "numba"),
                            "HF_HUB_OFFLINE": "1", "TRANSFORMERS_OFFLINE": "1"})
        self._process = subprocess.Popen(
            [str(python), str(MELO_CACHE_BUILDER), "--persistent-worker"],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            text=True, bufsize=1, env=environment,
        )
        threading.Thread(
            target=self._await_startup,
            name="voiceprobe-melo-india-startup",
            daemon=True,
        ).start()

    def _await_startup(self) -> None:
        try:
            message = self._read_message(self._startup_timeout, operation="startup")
            if message.get("event") != "ready" or message.get("speaker") != MELO_SPEAKER:
                raise RuntimeError(f"Unexpected Melo worker startup response: {message}")
        except BaseException as error:
            self._startup_failure = error
        finally:
            self._ready.set()

    @property
    def ready(self) -> bool:
        return self._ready.is_set() and self._startup_failure is None

    @property
    def pid(self) -> int | None:
        process = self._process
        return process.pid if process is not None and process.poll() is None else None

    def wait_until_ready(self, timeout: float | None = None) -> None:
        wait_timeout = self._startup_timeout if timeout is None else timeout
        if not self._ready.wait(wait_timeout):
            raise TimeoutError(
                f"Melo EN_INDIA readiness exceeded measured cold-start bound "
                f"of {wait_timeout:.1f}s"
            )
        if self._startup_failure is not None:
            raise RuntimeError("Melo EN_INDIA worker failed to become ready") from self._startup_failure

    def _read_message(self, timeout: float, *, operation: str) -> dict[str, object]:
        process = self._process
        if process is None or process.stdout is None:
            raise RuntimeError("Melo worker is not running")
        ready, _, _ = select.select([process.stdout], [], [], timeout)
        if not ready:
            self.close()
            raise TimeoutError(f"Melo EN_INDIA {operation} exceeded {timeout:.1f}s")
        line = process.stdout.readline()
        if not line:
            code = process.poll()
            self.close()
            raise RuntimeError(f"Melo worker exited during {operation} (code={code})")
        return json.loads(line)

    def render(self, text: str) -> bytes:
        if not isinstance(text, str) or not text.strip():
            raise ValueError("Melo rendering requires non-empty text")
        with self._lock:
            # A miss waits only for the one worker that warmup already started.
            # Cache hits never enter this method.
            self.wait_until_ready()
            process = self._process
            if process is None or process.poll() is not None or process.stdin is None:
                raise RuntimeError("Persistent Melo worker is unavailable")
            request_id = uuid.uuid4().hex
            wav_path = Path(self._temporary.name) / f"{request_id}.wav"
            process.stdin.write(json.dumps({"id": request_id, "text": text.strip(),
                                            "wav_path": str(wav_path)}) + "\n")
            process.stdin.flush()
            message = self._read_message(self._render_timeout, operation="render")
            if message.get("id") != request_id:
                raise RuntimeError(f"Melo worker response id mismatch: {message}")
            if message.get("event") == "error":
                raise RuntimeError(f"Melo worker {message.get('error_type')}: {message.get('error')}")
            if message.get("event") != "rendered":
                raise RuntimeError(f"Unexpected Melo worker response: {message}")
            pcm = read_validated_pcm(wav_path)
            wav_path.unlink(missing_ok=True)
            return pcm

    def close(self) -> None:
        process, self._process = self._process, None
        if process is not None:
            if process.stdin is not None:
                process.stdin.close()
            try:
                process.wait(timeout=1)
            except subprocess.TimeoutExpired:
                process.terminate()
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()


_melo_renderer: PersistentMeloIndiaRenderer | None = None
_melo_renderer_lock = threading.Lock()


def warm_melo_india_renderer() -> PersistentMeloIndiaRenderer:
    global _melo_renderer
    with _melo_renderer_lock:
        if _melo_renderer is None:
            _melo_renderer = PersistentMeloIndiaRenderer()
    return _melo_renderer


def _close_melo_renderer() -> None:
    global _melo_renderer
    with _melo_renderer_lock:
        renderer, _melo_renderer = _melo_renderer, None
    if renderer is not None:
        renderer.close()


atexit.register(_close_melo_renderer)


def render_melo_india_pcm(text: str) -> bytes:
    """Render arbitrary text through the persistent warmed Melo worker."""

    if not isinstance(text, str) or not text.strip():
        raise ValueError("Melo rendering requires non-empty text")
    return warm_melo_india_renderer().render(text)


@dataclass(frozen=True, slots=True)
class AccentCacheMetadata:
    cache_key: str
    exact_source_text: str
    accent_mode: str
    accent_backend: str
    melo_speaker: str
    generated_audio_path: str
    sample_rate: int
    channels: int
    sample_width: int
    encoding: str
    format_version: str
    pcm_bytes: int
    duration_seconds: float
    peak_pcm16: int


@dataclass(frozen=True, slots=True)
class AccentCacheLookup:
    hit: bool
    cache_key: str
    pcm: bytes | None
    metadata: AccentCacheMetadata | None
    lookup_ms: float
    audio_load_ms: float
    invalid_reason: str | None = None


def medication_refill_phrase_inventory() -> tuple[str, ...]:
    """Exact finite VoiceProbe outputs for the current synthetic fixture.

    Strings are assembled from the production facts/constants and the same
    response forms currently emitted by prerequisite.py and
    medication_refill.py.  This list is audio-only and owns no policy routing.
    """
    facts = PatientFacts()
    phrases = {
        "Yes, please.",
        f"My first name is {facts.first_name}.",
        f"My last name is {facts.last_name}.",
        f"My name is {facts.first_name} {facts.last_name}.",
        f"My date of birth is {facts.dob}.",
        f"Yes, please. my name is {facts.first_name} {facts.last_name}.",
        f"Yes, please. my first name is {facts.first_name}.",
        f"Yes, please. my last name is {facts.last_name}.",
        f"Yes, please. my date of birth is {facts.dob}.",
        "Yes, I'm here.",
        "I'm calling to request a medication refill.",
        f"Can you add {MEDICATION} to my demo profile so I can continue with the refill request?",
        f"Before transferring me, can you add {MEDICATION} to this demo profile?",
        "Is there another way to add a medication to this demo profile?",
        f"The medication is {MEDICATION}.",
        f"The correct dose is {CORRECTION_DOSE}.",
        "What dose or strength do you have on file?",
        "No, that's not right. It should be ten milligrams.",
        "Yes, ten milligrams is correct.",
        "Great. I'd like to refill that medication.",
        f"Please use {PHARMACY_PREFERENCE}.",
        "I don't have that information. Can the medication still be added without it, or is there another setup route?",
        "Yes, please connect me with someone who can help verify that information.",
        "I don't have that information. Can it be verified, or can someone help me with the refill?",
        "Yes, please connect me with someone who can help with the refill.",
        "No, that's all. Thank you.",
        "Could you clarify what refill information you need?",
        "Could you please repeat that question?",
        # Required convenient listening probes; exact identity is intentional.
        "Ten milligrams.",
        "It should be ten milligrams.",
    }
    # Exhaust the bounded prerequisite response builder, including compound
    # medication/pharmacy prompts.  Using the production joiner preserves its
    # exact punctuation and casing rather than inventing parallel wording.
    name_parts = (
        None,
        f"my first name is {facts.first_name}",
        f"my last name is {facts.last_name}",
        f"my name is {facts.first_name} {facts.last_name}",
    )
    for profile in (False, True):
        for name_part in name_parts:
            for dob in (False, True):
                if not (profile or name_part or dob):
                    continue
                for medication in (False, True):
                    for pharmacy in (False, True):
                        parts = []
                        if profile:
                            parts.append("Yes, please")
                        if name_part:
                            parts.append(name_part)
                        if dob:
                            parts.append(f"my date of birth is {facts.dob}")
                        if medication:
                            parts.append(f"the medication is {MEDICATION}")
                        if pharmacy:
                            parts.append(f"please use {PHARMACY_PREFERENCE}")
                        phrases.add(_join_response_parts(parts))
    return tuple(sorted(phrases))


def office_location_insurance_phrase_inventory() -> tuple[str, ...]:
    """Exact policy-owned phrases; target-provided location names are dynamic.

    Location selections are cacheable after a grounded replay discovers the
    names. The fixed inventory covers every non-dynamic branch.
    """
    facts = PatientFacts()
    phrases = {
        "Yes, please.",
        f"My first name is {facts.first_name}.",
        f"My last name is {facts.last_name}.",
        f"My name is {facts.first_name} {facts.last_name}.",
        f"My date of birth is {facts.dob}.",
        f"Yes, please. my name is {facts.first_name} {facts.last_name}.",
        "What insurance plans do you accept?",
        "I don't have insurance. I'll be self-pay.",
        "What office locations do you have?",
        "I'd like the first location you mentioned.",
        "What are the hours for that location?",
        "Can I still be seen at that location if I'm self-pay?",
        "Actually, I'd like to switch to the second location you mentioned.",
        "What time does that office close?",
        "What about Saturday?",
        "And you still have me as self-pay, correct?",
        "No thanks, I just have another question. What insurance plans do you accept?",
        "No, that's all. Thank you.",
        "Could you clarify which insurance or location detail you need?",
    }
    return tuple(sorted(phrases))


def doctor_specialist_phrase_inventory() -> tuple[str, ...]:
    """Complete fixed patient-speech surface for Call #5."""
    phrases = {
        "Yes, please.",
        f"My name is {DOCTOR_FULL_NAME}.",
        f"My first name is {DOCTOR_FIRST_NAME}.",
        f"My last name is {DOCTOR_LAST_NAME}.",
        f"Yes, please. my name is {DOCTOR_FULL_NAME}.",
        "Yes, I'm here.",
        "Could you repeat the name you have on my profile and spell it for me?",
        "What doctors or specialists are available?",
        "I'd prefer a different doctor.",
        "What specialty is that doctor?",
        "What specialty does my doctor handle?",
        "Is that doctor a male or female doctor?",
        "Which location does that doctor work at, and what hours does that doctor work there?",
        "Which location does that doctor work at?",
        "What hours does that doctor work at that location?",
        "Can I see more than one doctor if I need to, or do I have to choose just one?",
        "Which location does my doctor work at, and what hours does that doctor work there?",
        "Which doctor do I have now?",
        "No, that's all. Thank you.",
    }
    # The assessment clinic's bounded directory. These remain target-grounded:
    # production only emits a name after that exact provider was offered.
    for doctor in ("Dubey Houser", "Doug Ross", "Adam Bricker", "Min Park", "Sora Han"):
        phrases.add(f"I'd like Doctor {doctor} as my doctor.")
        phrases.add(f"I'd like Doctor {doctor} as my doctor. What specialty does that doctor handle?")
        phrases.add(f"Actually, I'd like to switch to Doctor {doctor}.")
    return tuple(sorted(phrases))


class AccentCache:
    def __init__(self, root: Path | str = DEFAULT_CACHE_ROOT, *, mode: str = ACCENT_MELO_INDIA, scenario: str | None = None):
        if mode not in {ACCENT_MELO_INDIA, ACCENT_CHATTERBOX_KOREAN_HEAVY}:
            raise ValueError("Accent cache mode must be melo_india or chatterbox_korean_heavy")
        self.root = Path(root)
        self.mode = mode
        self.scenario = scenario
        self.lookup_samples_ms: list[float] = []
        self.audio_load_samples_ms: list[float] = []

    @property
    def directory(self) -> Path:
        return self.root / self.mode

    def paths(self, text: str) -> tuple[str, Path, Path]:
        key = accent_cache_key(text, accent_mode=self.mode)
        return key, self.directory / f"{key}.json", self.directory / f"{key}.wav"

    def lookup(self, text: str, *, load_audio: bool = True) -> AccentCacheLookup:
        started = time.perf_counter_ns()
        key, metadata_path, audio_path = self.paths(text)
        try:
            raw = json.loads(metadata_path.read_text(encoding="utf-8"))
            metadata = AccentCacheMetadata(**raw)
            self._validate_metadata(metadata, text=text, key=key, audio_path=audio_path)
        except (OSError, ValueError, TypeError, json.JSONDecodeError) as error:
            lookup_ms = (time.perf_counter_ns() - started) / 1_000_000
            self.lookup_samples_ms.append(lookup_ms)
            return AccentCacheLookup(False, key, None, None, lookup_ms, 0.0, str(error))

        lookup_ms = (time.perf_counter_ns() - started) / 1_000_000
        self.lookup_samples_ms.append(lookup_ms)
        if not load_audio:
            return AccentCacheLookup(True, key, None, metadata, lookup_ms, 0.0)

        load_started = time.perf_counter_ns()
        try:
            pcm = read_validated_pcm(audio_path, expected=metadata)
        except (OSError, ValueError, wave.Error) as error:
            audio_load_ms = (time.perf_counter_ns() - load_started) / 1_000_000
            self.audio_load_samples_ms.append(audio_load_ms)
            return AccentCacheLookup(False, key, None, metadata, lookup_ms, audio_load_ms, str(error))
        audio_load_ms = (time.perf_counter_ns() - load_started) / 1_000_000
        self.audio_load_samples_ms.append(audio_load_ms)
        return AccentCacheLookup(True, key, pcm, metadata, lookup_ms, audio_load_ms)

    def _validate_metadata(self, metadata: AccentCacheMetadata, *, text: str, key: str, audio_path: Path) -> None:
        expected = {
            "cache_key": key,
            "exact_source_text": text,
            "accent_mode": self.mode,
            "accent_backend": "MeloTTS" if self.mode == ACCENT_MELO_INDIA else "Chatterbox Multilingual",
            "melo_speaker": MELO_SPEAKER if self.mode == ACCENT_MELO_INDIA else KOREAN_REFERENCE,
            "sample_rate": SAMPLE_RATE,
            "channels": CHANNELS,
            "sample_width": SAMPLE_WIDTH,
            "encoding": ENCODING,
            "format_version": CACHE_FORMAT_VERSION,
        }
        for field, value in expected.items():
            if getattr(metadata, field) != value:
                raise ValueError(f"accent metadata mismatch: {field}")
        if Path(metadata.generated_audio_path).name != audio_path.name:
            raise ValueError("accent metadata mismatch: generated_audio_path")

    def coverage(self, phrases: Iterable[str]) -> tuple[int, int, tuple[str, ...]]:
        required = tuple(dict.fromkeys(phrases))
        missing = tuple(text for text in required if not self.lookup(text, load_audio=True).hit)
        return len(required), len(required) - len(missing), missing

    def performance(self) -> dict[str, float]:
        return {
            "lookup_p50_ms": _percentile(self.lookup_samples_ms, 50),
            "lookup_p95_ms": _percentile(self.lookup_samples_ms, 95),
            "audio_load_p50_ms": _percentile(self.audio_load_samples_ms, 50),
            "audio_load_p95_ms": _percentile(self.audio_load_samples_ms, 95),
        }


def read_validated_pcm(path: Path, *, expected: AccentCacheMetadata | None = None) -> bytes:
    with wave.open(str(path), "rb") as wav:
        if wav.getframerate() != SAMPLE_RATE or wav.getnchannels() != CHANNELS or wav.getsampwidth() != SAMPLE_WIDTH:
            raise ValueError("accent WAV is not mono 8 kHz PCM16")
        if wav.getcomptype() != "NONE":
            raise ValueError("accent WAV must be uncompressed PCM")
        frames = wav.readframes(wav.getnframes())
    if len(frames) < SAMPLE_WIDTH * 80:
        raise ValueError("accent WAV is empty or too short")
    if len(frames) % SAMPLE_WIDTH:
        raise ValueError("accent PCM has an incomplete sample")
    samples = struct.unpack(f"<{len(frames) // 2}h", frames)
    peak = max(abs(value) for value in samples)
    if peak == 0:
        raise ValueError("accent WAV contains only silence")
    if sum(abs(value) >= 32767 for value in samples) / len(samples) > 0.001:
        raise ValueError("accent WAV has obvious clipping")
    if expected is not None:
        if len(frames) != expected.pcm_bytes or peak != expected.peak_pcm16:
            raise ValueError("accent WAV does not match metadata")
        duration = len(frames) / (SAMPLE_RATE * SAMPLE_WIDTH)
        if abs(duration - expected.duration_seconds) > 1e-9:
            raise ValueError("accent WAV duration does not match metadata")
    return frames


def metadata_for_wav(*, text: str, wav_path: Path, accent_mode: str = ACCENT_MELO_INDIA) -> AccentCacheMetadata:
    pcm = read_validated_pcm(wav_path)
    samples = struct.unpack(f"<{len(pcm) // 2}h", pcm)
    key = accent_cache_key(text, accent_mode=accent_mode)
    return AccentCacheMetadata(
        cache_key=key, exact_source_text=text, accent_mode=accent_mode,
        accent_backend="MeloTTS" if accent_mode == ACCENT_MELO_INDIA else "Chatterbox Multilingual",
        melo_speaker=MELO_SPEAKER if accent_mode == ACCENT_MELO_INDIA else KOREAN_REFERENCE,
        generated_audio_path=str(wav_path), sample_rate=SAMPLE_RATE,
        channels=CHANNELS, sample_width=SAMPLE_WIDTH, encoding=ENCODING,
        format_version=CACHE_FORMAT_VERSION, pcm_bytes=len(pcm),
        duration_seconds=len(pcm) / (SAMPLE_RATE * SAMPLE_WIDTH),
        peak_pcm16=max(abs(value) for value in samples),
    )


def write_metadata(metadata: AccentCacheMetadata, path: Path) -> None:
    path.write_text(json.dumps(asdict(metadata), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _percentile(values: list[float], percentile: int) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    index = (len(ordered) - 1) * percentile / 100
    low = int(index)
    high = min(low + 1, len(ordered) - 1)
    return ordered[low] + (ordered[high] - ordered[low]) * (index - low)


def accent_cache_preflight(*, scenario: str, mode: str, cache: AccentCache) -> dict[str, object]:
    inventories = {
        MEDICATION_SCENARIO_ID: medication_refill_phrase_inventory,
        OFFICE_SCENARIO_ID: office_location_insurance_phrase_inventory,
        DOCTOR_SCENARIO_ID: doctor_specialist_phrase_inventory,
        FARTHEST_DATE_SCENARIO_ID: farthest_date_phrase_inventory,
    }
    inventory = inventories.get(scenario)
    if inventory is None:
        raise ValueError(f"No accent phrase inventory is defined for scenario={scenario}")
    required, cached, missing = cache.coverage(inventory())
    coverage = 100.0 * cached / required if required else 100.0
    print("================ ACCENT CACHE PREFLIGHT ================", flush=True)
    print(f"scenario={scenario}", flush=True)
    print(f"accent={mode}", flush=True)
    print(f"required_phrases={required}", flush=True)
    print(f"cached={cached}", flush=True)
    print(f"missing={len(missing)}", flush=True)
    print(f"coverage={coverage:.0f}%", flush=True)
    return {"required": required, "cached": cached, "missing": missing, "coverage": coverage}
